/**
 * Gitlawb SDK — persistent data + user sign-in for this app.
 * Zero config: works in the playground preview AND after publishing.
 * Do not edit this file; import from it.
 *
 *   import { gitlawb } from "./lib/gitlawb";   // adjust relative path
 *
 *   // A collection is a named bag of JSON records belonging to THIS app.
 *   const todos = gitlawb.db.collection("todos");                      // private per user (default)
 *   const posts = gitlawb.db.collection("posts", { visibility: "public" }); // everyone reads+writes
 *
 *   await todos.create({ text: "hello", done: false });
 *   const { records } = await todos.list();            // [{ id, data, mine, ownerKey, createdAt }]
 *   await todos.update(records[0].id, { done: true }); // shallow-merges fields
 *   await todos.remove(records[0].id);
 *
 *   // Sign-in ("Sign in with Gitlawb") — needed for private/authenticated data:
 *   gitlawb.auth.user();     // { id, name? } | null   (id is anonymous + app-scoped)
 *   gitlawb.auth.signIn();   // redirects to gitlawb sign-in, returns to this page
 *   gitlawb.auth.signOut();
 *
 * Visibility (enforced by the platform):
 *   "public"        — anyone can read; anyone can create; authors edit their own records
 *   "authenticated" — signed-in users read all records and create; authors edit their own
 *   "owner"         — each signed-in user only ever sees THEIR OWN records (default)
 *   "inbox"         — anyone can submit WITHOUT signing in; only the builder reads
 *
 * Requesting "public" or "authenticated" does NOT apply immediately: strangers
 * being able to read records is a decision only the app's builder can make, so
 * the collection is created private and the request shows up in the Data tab
 * for the builder to allow. "owner" and "inbox" apply right away. Once a
 * collection IS public/authenticated, changing its mode from code is also a
 * no-op — only the builder's Data tab can. Never put personal data (profiles,
 * members, accounts, contact info) in a public collection.
 */

const API_ORIGIN = "https://playground.gitlawb.com";

type Visibility = "public" | "authenticated" | "owner" | "inbox";

export type GitlawbRecord<T = Record<string, unknown>> = {
  id: string;
  data: T;
  /** Anonymous, app-scoped author id (null for anonymous writes). */
  ownerKey: string | null;
  /** True when the current caller created this record. */
  mine: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ListOptions = {
  limit?: number;
  /** ISO timestamp cursor — pass the previous page's `nextBefore`. */
  before?: string;
  /** Only records created by the current user. */
  mine?: boolean;
  /**
   * Sort by a top-level data field, e.g. "name:asc". Compares as TEXT, so
   * numbers order lexicographically ("9" > "100") — for numeric ranking,
   * list() and sort in JS. Default: newest first. Note: cursor pagination
   * (`nextBefore`) is only available on the default sort.
   */
  sort?: string;
};

type Env =
  | { mode: "published"; appId: string; base: string }
  | { mode: "preview"; sessionId: string; base: "" }
  | { mode: "unknown" };

function detectEnv(): Env {
  if (typeof document !== "undefined") {
    const meta = document.querySelector('meta[name="gitlawb-app-id"]');
    const id = meta?.getAttribute("content");
    if (id) return { mode: "published", appId: id, base: API_ORIGIN };
  }
  if (typeof location !== "undefined") {
    const m = location.pathname.match(
      /\/api\/preview\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(\/|$)/i,
    );
    if (m) return { mode: "preview", sessionId: m[1], base: "" };
  }
  return { mode: "unknown" };
}

const env = detectEnv();

/** sessionStorage access that never throws (it can be blocked outright). */
const ss = {
  get(k: string): string | null {
    try {
      return sessionStorage.getItem(k);
    } catch {
      return null;
    }
  },
  set(k: string, v: string): void {
    try {
      sessionStorage.setItem(k, v);
    } catch {
      /* storage unavailable — behave as a cache miss */
    }
  },
};

/** The builder's own app-scoped id in preview, so `auth.user().id` matches the
 *  `ownerKey` on records they write — the same as it does for a signed-in
 *  visitor on the published app. */
let previewUserKey: string | null = null;

// ---- app id resolution -------------------------------------------------------

let appIdPromise: Promise<string> | null = null;
function appId(): Promise<string> {
  if (appIdPromise) return appIdPromise;
  const pending = (async () => {
    if (env.mode === "published") return env.appId;
    if (env.mode === "preview") {
      const cached = ss.get(`glb:app:${env.sessionId}`);
      if (cached) {
        previewUserKey = ss.get(`glb:me:${env.sessionId}`);
        return cached;
      }
      const res = await fetch(`/api/data/ctx?session=${env.sessionId}`);
      if (!res.ok) throw new Error("gitlawb: could not resolve app context in preview");
      const { appId, userKey } = (await res.json()) as { appId: string; userKey?: string | null };
      ss.set(`glb:app:${env.sessionId}`, appId);
      if (userKey) {
        previewUserKey = userKey;
        ss.set(`glb:me:${env.sessionId}`, userKey);
      }
      return appId;
    }
    throw new Error("gitlawb: unknown environment (not preview or published)");
  })();
  // Don't cache a rejection: a transient failure resolving the app context
  // would otherwise poison every later call for the life of the page.
  appIdPromise = pending;
  pending.catch(() => {
    if (appIdPromise === pending) appIdPromise = null;
  });
  return pending;
}

// ---- auth -------------------------------------------------------------------

function tokenKey(app: string): string {
  return `glb:token:${app}`;
}

function stateKey(app: string): string {
  return `glb:state:${app}`;
}

/**
 * Capture #glbtoken=... after returning from /data-auth (published only).
 *
 * A token is ONLY accepted when it carries the one-time `state` this SDK
 * generated for a sign-in it started. Without that check, anyone could hand a
 * victim a link ending in #glbtoken=<their own token>, silently signing the
 * victim into the ATTACKER's account — everything the victim then saved would
 * be written to the attacker's records.
 */
function captureTokenFromHash(): void {
  if (typeof location === "undefined" || env.mode !== "published") return;
  const token = location.hash.match(/[#&]glbtoken=([A-Za-z0-9_.-]+)/);
  if (!token) return;
  const state = location.hash.match(/[#&]state=([A-Za-z0-9_-]+)/);
  let expected: string | null = null;
  try {
    expected = sessionStorage.getItem(stateKey(env.appId));
    sessionStorage.removeItem(stateKey(env.appId)); // single use
  } catch {
    /* storage unavailable */
  }
  // Always scrub the fragment, accepted or not.
  history.replaceState(null, "", location.pathname + location.search);
  if (!expected || !state || state[1] !== expected) return; // unsolicited — drop it
  try {
    localStorage.setItem(tokenKey(env.appId), token[1]);
  } catch {
    /* storage unavailable — session-only auth */
  }
}
captureTokenFromHash();

function storedToken(): string | null {
  if (env.mode !== "published") return null;
  try {
    const token = localStorage.getItem(tokenKey(env.appId));
    if (!token) return null;
    const claims = decodeClaims(token);
    if (!claims || claims.exp * 1000 < Date.now()) {
      localStorage.removeItem(tokenKey(env.appId));
      return null;
    }
    return token;
  } catch {
    return null;
  }
}

type Claims = { sub: string; name?: string; role: string; exp: number };
function decodeClaims(token: string): Claims | null {
  try {
    const payload = token.split(".")[1];
    return JSON.parse(atob(payload.replace(/-/g, "+").replace(/_/g, "/"))) as Claims;
  } catch {
    return null;
  }
}

const auth = {
  /** Current user: `{ id, name? }` or null. In preview you are always signed in as the builder. */
  user(): { id: string; name?: string } | null {
    // `id` is the same app-scoped key that lands in `record.ownerKey`, so
    // `records.filter(r => r.ownerKey === user().id)` behaves identically in
    // preview and after publishing.
    if (env.mode === "preview") return { id: previewUserKey ?? "owner", name: "you (builder)" };
    const token = storedToken();
    if (!token) return null;
    const claims = decodeClaims(token);
    return claims ? { id: claims.sub, name: claims.name } : null;
  },
  /** Redirect to gitlawb sign-in; the user comes straight back to this page. */
  signIn(): void {
    if (env.mode !== "published") return; // preview is already authenticated
    // One-time nonce binding this sign-in to the token we get back.
    const bytes = new Uint8Array(16);
    crypto.getRandomValues(bytes);
    const state = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
    try {
      sessionStorage.setItem(stateKey(env.appId), state);
    } catch {
      /* storage unavailable — sign-in will be rejected on return; nothing unsafe happens */
    }
    const redirect = encodeURIComponent(location.href.split("#")[0]);
    location.href = `${API_ORIGIN}/data-auth?app=${env.appId}&redirect=${redirect}&state=${state}`;
  },
  signOut(): void {
    if (env.mode === "published") {
      try {
        localStorage.removeItem(tokenKey(env.appId));
      } catch {
        /* ignore */
      }
    }
  },
};

// ---- http -------------------------------------------------------------------

async function api(path: string, init?: RequestInit): Promise<Response> {
  const app = await appId();
  const headers = new Headers(init?.headers);
  if (init?.body) headers.set("Content-Type", "application/json");
  const token = storedToken();
  if (token) headers.set("Authorization", `Bearer ${token}`);
  const res = await fetch(`${env.mode === "published" ? API_ORIGIN : ""}/api/data/${app}${path}`, {
    ...init,
    headers,
  });
  if (res.status === 401 && env.mode === "published") {
    // Token missing/expired — surface a typed error the app can catch to call signIn().
    const body = (await res.json().catch(() => ({}))) as { error?: string };
    const err = new Error(body.error === "invalid_token" ? "gitlawb: sign-in expired" : "gitlawb: sign-in required");
    (err as Error & { code: string }).code = "sign_in_required";
    throw err;
  }
  if (!res.ok && res.status !== 204) {
    const body = (await res.json().catch(() => ({}))) as { message?: string; error?: string };
    const err = new Error(body.message || `gitlawb: request failed (${res.status})`);
    (err as Error & { code?: string }).code = body.error;
    throw err;
  }
  return res;
}

// ---- collections ------------------------------------------------------------

const ensured = new Set<string>();

function collection<T extends Record<string, unknown> = Record<string, unknown>>(
  name: string,
  opts?: { visibility?: Visibility },
) {
  const ensure = async (): Promise<void> => {
    if (ensured.has(name)) return;
    // Only the builder, in the playground preview, can create a collection.
    // In a published app this call could only ever 403 — and it counts against
    // the visitor's write rate limit, so firing it on every page load would
    // spend their budget on a request that cannot succeed.
    if (env.mode !== "preview") {
      ensured.add(name);
      return;
    }
    // Runs even with no visibility option: this is what actually CREATES the
    // collection, and it only succeeds for the builder (in the playground
    // preview). Without it, a collection that is never written to during
    // development doesn't exist when the published app first reads it, and
    // every visitor gets "no such collection". Omitting `visibility` means
    // create-if-missing — it never rewrites an existing collection's setting.
    // Survives HMR reloads: the agent's edits reload the iframe constantly,
    // and re-sending this PUT each time would spend the write rate limit on
    // work that's already done. Keyed by name AND requested visibility — if
    // the code changes the option mid-session, the new request must go out
    // (it may need the builder's approval) rather than hit a stale cache.
    const key = `glb:ens:${name}:${opts?.visibility ?? "default"}`;
    if (ss.get(key)) {
      ensured.add(name);
      return;
    }
    try {
      const res = await api(`/${name}`, {
        method: "PUT",
        body: JSON.stringify(opts?.visibility ? { visibility: opts.visibility } : {}),
      });
      // Widening to public/authenticated needs the builder's approval in the
      // Data tab; until then the platform keeps the collection private. Say so
      // in the console rather than failing — reads/writes still work for the
      // builder in preview, so the app develops normally either way.
      const body = (await res.json().catch(() => null)) as
        | { approvalRequired?: boolean; visibility?: string; message?: string }
        | null;
      if (body?.approvalRequired) {
        console.warn(
          `gitlawb: "${name}" was created ${body.visibility ?? "private"} — ` +
            `"${opts?.visibility}" needs approval in the Data tab before visitors get that access.`,
        );
      }
      ensured.add(name);
      ss.set(key, "1");
    } catch (e) {
      // Only give up permanently when the answer won't change. A 429/503 is
      // transient — caching it would leave the collection uncreated for the
      // life of the page and 404 every later call.
      const code = (e as { code?: string }).code;
      if (code === "owner_only" || code === "forbidden") ensured.add(name);
    }
  };

  return {
    async list(options: ListOptions = {}): Promise<{ records: GitlawbRecord<T>[]; nextBefore: string | null }> {
      await ensure();
      const params = new URLSearchParams();
      if (options.limit) params.set("limit", String(options.limit));
      if (options.before) params.set("before", options.before);
      if (options.mine) params.set("mine", "1");
      if (options.sort) params.set("sort", options.sort);
      const qs = params.toString();
      const res = await api(`/${name}${qs ? `?${qs}` : ""}`);
      return (await res.json()) as { records: GitlawbRecord<T>[]; nextBefore: string | null };
    },
    async get(id: string): Promise<GitlawbRecord<T>> {
      await ensure();
      const res = await api(`/${name}/${id}`);
      return (await res.json()) as GitlawbRecord<T>;
    },
    async create(data: T): Promise<GitlawbRecord<T>> {
      await ensure();
      const res = await api(`/${name}`, { method: "POST", body: JSON.stringify(data) });
      return (await res.json()) as GitlawbRecord<T>;
    },
    /** Shallow-merges the given top-level fields into the record. */
    async update(id: string, data: Partial<T>): Promise<GitlawbRecord<T>> {
      await ensure();
      const res = await api(`/${name}/${id}`, { method: "PATCH", body: JSON.stringify(data) });
      return (await res.json()) as GitlawbRecord<T>;
    },
    async remove(id: string): Promise<void> {
      await ensure();
      await api(`/${name}/${id}`, { method: "DELETE" });
    },
  };
}

export const gitlawb = { db: { collection }, auth };
